---
name: Run Unit Tests

on: push

jobs:
  test:
    name: Test Application
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Docker build
        run: |
          cd go
          docker build -t temp .
      - name: Docker publish
        run: |
          cd go
          docker tag temp asia.gcr.io/kargotech-prod/wibisana-excellerate:${{ github.sha }}
          docker tag temp asia.gcr.io/kargotech-prod/wibisana-excellerate:latest
          docker push asia.gcr.io/kargotech-prod/wibisana-excellerate:${{ github.sha }}
          docker push asia.gcr.io/kargotech-prod/wibisana-excellerate:latest
