---
name: Run Unit Tests

on: push

jobs:
  test:
    name: Test Application
    runs-on: ubuntu:20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Docker build
        run: |
          cd go
          docker build -t temp .
      - name: Docker publish
        run: |
          docker login -u carash -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag temp carash/excellerate-wibisana:${{ github.sha }}
          docker tag temp carash/excellerate-wibisana:latest
          docker push carash/excellerate-wibisana:${{ github.sha }}
          docker push carash/excellerate-wibisana:latest
