---
name: Build Docker Image

on:
  pull_request:
    branches: master

jobs:
  deploy:
    name: Build Application
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run unit tests
        run: |
          cd go
          go test .
